version: '3'
env:
  DOCKER: docker.exe

tasks:
  run-dev:
    cmds:
      - uv run uvicorn app.main:app --reload
    desc: Run uvicorn development server
  format:
    desc: Format code
    cmds:
      - uv run ruff format .
  lint:
    desc: Lint code
    cmds:
      - uv run ruff check .

# NEW TASK: Dependency to stop local service
# DATABASE TASKS
  db-local-stop:
    desc: "Stop and disable the local system PostgreSQL service (Linux/WSL only)."
    # WARNING: This will require a sudo password prompt.
    cmds:
      - sudo systemctl stop postgresql || true # || true ignores error if service isn't running
      - sudo systemctl disable postgresql || true

  db-up:
    desc: "Start PostgreSQL container"
    deps: [db-local-stop]
    cmds:
      - "{{.DOCKER}} compose up -d db"

  db-down:
    desc: "Stop PostgreSQL container"
    cmds:
      - "{{.DOCKER}} compose down"

  db-logs:
    desc: "View database logs"
    cmds:
      - "{{.DOCKER}} compose logs -f db"

  db-reset:
    desc: "Reset database (WARNING: destroys all data)"
    deps: [db-local-stop]
    cmds:
      - "{{.DOCKER}} compose down -v"
      - "{{.DOCKER}} compose up -d db"

  db-migrate:
    desc: "Run database migrations"
    cmds:
      - alembic upgrade head

  db-migrate-create:
    desc: "Create new migration (usage: task db:migrate:create -- 'message')"
    cmds:
      - alembic revision --autogenerate -m "{{.CLI_ARGS}}"

  db-rollback:
    desc: "Rollback last migration"
    cmds:
      - alembic downgrade -1

  db-history:
    desc: "Show migration history"
    cmds:
      - alembic history

  # TESTING
  create-test-db:
    desc: "Create Testing Database"
    cmds:
      - '{{.DOCKER}} exec -it fastbin_db psql -U postgres -c "CREATE DATABASE fastbin_test;"'
      
  test-db:
    desc: "Run database tests"
    deps: [db-local-stop , create-test-db]
    cmds:
      - pytest tests/test_database.py -v
    
