"""'removed token blacklist and added token table'

Revision ID: 44b7e8ac1df0
Revises: b08ddf1f6c75
Create Date: 2025-11-26 08:36:11.764386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44b7e8ac1df0'
down_revision: Union[str, Sequence[str], None] = 'b08ddf1f6c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('pastes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('short_url', sa.String(length=20), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_expires_public', 'pastes', ['expires_at', 'is_public'], unique=False)
    op.create_index('idx_user_created', 'pastes', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_pastes_id'), 'pastes', ['id'], unique=False)
    op.create_index(op.f('ix_pastes_short_url'), 'pastes', ['short_url'], unique=True)
    op.create_index(op.f('ix_pastes_user_id'), 'pastes', ['user_id'], unique=False)
    op.create_table('tokens',
    sa.Column('jti', sa.UUID(), nullable=False),
    sa.Column('token_type', sa.String(length=30), nullable=False),
    sa.Column('paired_jti', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_blacklisted', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blacklist_reason', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jti', 'paired_jti')
    )
    op.create_index(op.f('ix_tokens_jti'), 'tokens', ['jti'], unique=False)
    op.create_index(op.f('ix_tokens_paired_jti'), 'tokens', ['paired_jti'], unique=False)
    op.create_index(op.f('ix_tokens_user_id'), 'tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_user_id'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_paired_jti'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_jti'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_pastes_user_id'), table_name='pastes')
    op.drop_index(op.f('ix_pastes_short_url'), table_name='pastes')
    op.drop_index(op.f('ix_pastes_id'), table_name='pastes')
    op.drop_index('idx_user_created', table_name='pastes')
    op.drop_index('idx_expires_public', table_name='pastes')
    op.drop_table('pastes')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
